### PR TITLE
Update links (and some details)

### PR DESCRIPTION
**Pull request by severo**

### CODE REVIEW

**Comment by julien-c** [comment]
tagging @srush instead :)

**Comment by julien-c** [comment]
For context for @srush: over the next few months we want to start experimenting with @severo @lhoestq @albertvillanova and others on whether we can build a subset of the features of `datasets-viewer` directly on the dataset pages on the hub, with a faster/more scalable UX and also with support for user-namespaced datasets. Thoughts?

We'll loop you in in a couple of weeks :)

**Comment by srush** [comment]
Sounds great to me. We are definitely hitting the limits of streamlit. 

Let me know if I can help!

**Review by lhoestq — APPROVED** [review]
Thanks :) Feel free to ping me if you have questions or if I can help

**Comment by julien-c** [comment]
Do you guys know how to deploy this? 🙂

**Comment by lhoestq** [comment]
Yes I can redeploy the app, but this PR needs to be merged first: https://github.com/huggingface/datasets-viewer/pull/14

**Pull request merged**
